// GENERATED by scripts/inline-csp-hashes.mjs - do not edit by hand.
//
// SHA-256 of every inline <script> and <style> in the build, named directly in
// the Content-Security-Policy. Regenerated by `npm run build`; a stale copy
// here would block the site's own inline code, so never hand-edit it.
//
// 20 page(s) scanned.

export const INLINE_SCRIPT_HASHES = [
  "sha256-0sxvQxDRjMb7eB222IpJeYAAONlOtkPqLWI5sDsYzvE=",
  "sha256-2W2d+cmIwKn40LAVRFyMXfX9RzGANXbT9gFabH8UbUI=",
  "sha256-8KpYZpeIfE8Z83xVfTZfp1b1RkwjNjigtx9crYAubeg=",
  "sha256-NsWGk8R1KUnYxi9H+caYuBLRDf1rsh3+wTfC637Of2E=",
  "sha256-O3xqdiHmmUTIHy3q/4Gh2rn/fqz+riEiDpgpQmarzfA=",
  "sha256-XzSsAYpQvnal6ASUww76WaLc8zNnzovr8TQqrCGQFZ0=",
  "sha256-YPa1sjLx0jTUF56oTfMtOX0Bt1MbEufP24nPNbgTwrw=",
  "sha256-Ya0pUYrC7nM5Cn/056TyVuEiz6dFGrzmkWzgON0pF0U=",
  "sha256-eIXWvAmxkr251LJZkjniEK5LcPF3NkapbJepohwYRIc=",
  "sha256-gHNzIl4YYj61DDLA0Ow55u4SQhUA9jPqvls9xzfs8RQ=",
  "sha256-k84nUsyBr8m7Rx5191SOtiyLT+hPEHZq/jSUGwCYgpQ=",
  "sha256-oZiDBYCnKxZ4d8LuC+XQlapjZJs3UGzz00Q1D/kyBX0=",
  "sha256-rMll8fQ85/q5CTgEafnUVe8Tydn2B81sjEi9iZ+IE6U=",
  "sha256-whf74ZTGRvRF1yBo1JPJBxEPBJdqiHR3lEb91E4TKCA=",
  "sha256-xBWm0Mw9/DB8UoPnyMb2JvXhQ709rcMkyOhe8LmMr6A="
];

export const INLINE_STYLE_HASHES = [
  "sha256-7lSt/drPj72MzHNeJ7jSQppooq8QZa61KAUs1NtdeYw=",
  "sha256-JawmqvBTkrXKuxNp9oqIhYmHFjXcpvJogBw5KtD2VdA=",
  "sha256-KTzcsNbAZG6ErAabuOaIZMTpAlNF2rIY7vx3a0Ozo3c=",
  "sha256-O6mNey0vjdD882rQTOyDP+xHXS0ggXWI2AS5KQ92XHE=",
  "sha256-TUs6CS5Lm8eT+jyGpMzIor/ToBHrMbrTMKM6McBqLfs=",
  "sha256-UcZPHgThR5Sep2Gyb0EbPNDZkQP5Bbo/XpbH0rGT6a4=",
  "sha256-aevZHH1xHklVsQlnJryOnk+Z9AobuvHPth50KpTPmFw=",
  "sha256-sZQNfUbT764Y/kpZvjL309G7MPft/AhQliRTk4oSmgI=",
  "sha256-sjxZKnx60ad3pZ0A9sx/A5WuQwhSm6PDnJNDnvRotIg=",
  "sha256-vl+RpbSP6ludkJB2CsbL4FP7MmVQRcKgiBKUxZtv4JM=",
  "sha256-vlUJjk8gp4cWBhyo//8gMSRnE2Wgqu98IprvdnOKmZE=",
  "sha256-vv9IoKo7BSLbWcUHr3tNmfNVmm5L/9Cfn2H6LMk7/ow="
];
